export const FINANCIAL_INSIGHT_LIMITS = {
  dashboard: 6,
  reports: 10,
} as const;

export const BUDGET_WARNING_THRESHOLD = 80;
export const BUDGET_DANGER_THRESHOLD = 100;

export const SPENDING_SPIKE_THRESHOLD = 0.3;
export const SPENDING_REDUCTION_THRESHOLD = 0.2;
export const SPENDING_MATERIAL_SHARE_THRESHOLD = 0.1;

export const CASH_FLOW_WARNING_THRESHOLD = 0.8;
export const CASH_FLOW_DANGER_THRESHOLD = 1;

export const DEBT_PRESSURE_WARNING_THRESHOLD = 0.3;
export const DEBT_PRESSURE_DANGER_THRESHOLD = 0.45;

export const GOAL_PROGRESS_GAP_THRESHOLD = 0.1;

export const EMERGENCY_FUND_DANGER_MONTHS = 1;
export const EMERGENCY_FUND_WARNING_MONTHS = 3;
export const EMERGENCY_FUND_SUCCESS_MONTHS = 6;

export const NET_WORTH_WARNING_THRESHOLD = -0.02;
export const NET_WORTH_DANGER_THRESHOLD = -0.05;
export const NET_WORTH_SUCCESS_THRESHOLD = 0.02;

export const INACTIVE_ACCOUNT_INFO_DAYS = 90;
export const INACTIVE_ACCOUNT_WARNING_DAYS = 180;

export const HIGH_CATEGORY_SPENDING_INFO_THRESHOLD = 0.3;
export const HIGH_CATEGORY_SPENDING_WARNING_THRESHOLD = 0.5;

export const UNUSUAL_TRANSACTION_MULTIPLIER = 3;
export const UNUSUAL_TRANSACTION_MIN_SAMPLES = 5;

export const INVESTMENT_EXPOSURE_THRESHOLD = 0.8;
export const INVESTMENT_CONCENTRATION_THRESHOLD = 0.5;

export const MULTI_CURRENCY_SHARE_THRESHOLD = 0.25;
